services:
  bot:
    build: ./bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    networks:
      - net0

  back:
    build: ./back
    networks:
      - net0
    ports:
      - "8080:8080"

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - net0

networks:
  net0:
